#!/usr/bin/env bash
# =============================================================================
# make-installer.sh – Builds the OomWatchdog self-extracting installer script
#
# Usage:
#   ./make-installer.sh [--output NAME]   default output: oom-watchdog-installer.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE_JAR="${SCRIPT_DIR}/core/target/oom-watchdog.jar"
HARNESS_JAR="${SCRIPT_DIR}/test-harness/target/test-harness.jar"
OUTPUT="oom-watchdog-installer.sh"

while [[ $# -gt 0 ]]; do
    case "$1" in --output) shift; OUTPUT="$1" ;; *) ;; esac; shift
done
OUTPUT="${SCRIPT_DIR}/${OUTPUT##*/}"

echo "==> Checking JARs..."
[[ -f "$CORE_JAR"    ]] || { echo "ERROR: $CORE_JAR not found. Run: mvn package"; exit 1; }
[[ -f "$HARNESS_JAR" ]] || { echo "ERROR: $HARNESS_JAR not found. Run: mvn package"; exit 1; }

WATCHDOG_SIZE=$(wc -c < "$CORE_JAR" | tr -d ' ')
HARNESS_SIZE=$(wc  -c < "$HARNESS_JAR" | tr -d ' ')
echo "==> Encoding oom-watchdog.jar  ($WATCHDOG_SIZE bytes)..."
echo "==> Encoding test-harness.jar  ($HARNESS_SIZE bytes)..."

{
  cat <<'SHEBANG'
#!/usr/bin/env bash
# =============================================================================
# OomWatchdog Self-Extracting Installer  (generated by make-installer.sh)
#
# Usage:
#   ./oom-watchdog-installer.sh [--install-dir <dir>]
#                               [--run-watchdog [watchdog-args...]]
#                               [--run-harness]
#                               [--help]
# =============================================================================
set -euo pipefail
SHEBANG

  # Emit size metadata as shell variables
  echo "WATCHDOG_JAR_BYTES=${WATCHDOG_SIZE}"
  echo "HARNESS_JAR_BYTES=${HARNESS_SIZE}"
  echo ""

  # Emit the base64 payloads as heredoc (no quoting issues)
  echo "read_watchdog_b64() { cat <<'__WATCHDOG_EOF__'"
  base64 < "$CORE_JAR"
  echo "__WATCHDOG_EOF__"
  echo "}"
  echo ""
  echo "read_harness_b64() { cat <<'__HARNESS_EOF__'"
  base64 < "$HARNESS_JAR"
  echo "__HARNESS_EOF__"
  echo "}"
  echo ""

  cat <<'BODY'
# =============================================================================
# Helpers
# =============================================================================

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "[OomWatchdog] $*"; }

require_java() {
    command -v java >/dev/null 2>&1 || die "java not found on PATH. Install JDK 8+."
    local raw
    raw=$(java -version 2>&1 | awk -F'"' 'NR==1{print $2}')
    local maj
    maj=$(echo "$raw" | sed 's/^1\.//' | cut -d. -f1)
    [[ "$maj" -ge 8 ]] 2>/dev/null || die "JDK $maj detected; need JDK 8+."
    info "Java $raw detected (OK)"
}

extract_jars() {
    local dir="$1"
    mkdir -p "$dir"
    info "Extracting oom-watchdog.jar  (${WATCHDOG_JAR_BYTES} bytes) → $dir/"
    read_watchdog_b64 | base64 --decode > "$dir/oom-watchdog.jar"
    info "Extracting test-harness.jar  (${HARNESS_JAR_BYTES} bytes) → $dir/"
    read_harness_b64  | base64 --decode > "$dir/test-harness.jar"
    info "Done."
}

print_help() {
cat <<HELP
OomWatchdog Self-Extracting Installer

Usage:
  ./oom-watchdog-installer.sh [options]

Options:
  --install-dir <dir>     Extract JARs to <dir>           (default: ./oom-watchdog)
  --run-watchdog [args]   Extract, then start the watchdog (remaining args forwarded)
  --run-harness           Extract, then run the test harness on a 96 MB heap
  --help                  Print this help and exit

Watchdog examples (pass after --run-watchdog):
  --dump-types heap,thread,class_histogram
  --warn-threshold 0.75 --crit-threshold 0.88
  --qradar-host 192.168.1.100

Test:
  ./oom-watchdog-installer.sh --run-harness

HELP
}

# =============================================================================
# Argument parsing
# =============================================================================
INSTALL_DIR="./oom-watchdog"
MODE="extract"
declare -a EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help)         print_help; exit 0 ;;
        --install-dir)  shift; INSTALL_DIR="$1" ;;
        --run-watchdog) MODE="watchdog"; shift; EXTRA_ARGS=("$@"); break ;;
        --run-harness)  MODE="harness" ;;
        *)              die "Unknown argument: $1  (use --help)" ;;
    esac
    shift
done

# =============================================================================
# Main
# =============================================================================
require_java
extract_jars "$INSTALL_DIR"

case "$MODE" in
    watchdog)
        info "Starting: java -jar $INSTALL_DIR/oom-watchdog.jar ${EXTRA_ARGS[*]:-}"
        exec java -jar "$INSTALL_DIR/oom-watchdog.jar" "${EXTRA_ARGS[@]:-}"
        ;;
    harness)
        info "Starting test harness: java -Xmx96m -jar $INSTALL_DIR/test-harness.jar"
        exec java -Xmx96m -jar "$INSTALL_DIR/test-harness.jar"
        ;;
    extract)
        info "JARs extracted to: $INSTALL_DIR"
        info "Watchdog:  java -jar $INSTALL_DIR/oom-watchdog.jar --help"
        info "Harness:   java -Xmx96m -jar $INSTALL_DIR/test-harness.jar"
        ;;
esac
BODY
} > "$OUTPUT"

chmod +x "$OUTPUT"

FINAL_SIZE=$(wc -c < "$OUTPUT" | tr -d ' ')
echo "==> Generated: $OUTPUT  (${FINAL_SIZE} bytes)"
echo ""
echo "Quick smoke-test:"
echo "  bash $OUTPUT --install-dir /tmp/oom-test"
